services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
#    image: otel/opentelemetry-collector-contrib-dev:latest
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
      - ./build/tmp:/tmp
    command: [ "--config=/otel-config.yaml" ]
    ports:
      - "4317:4317/tcp"
    networks:
      - log_network
  vector:
    image: timberio/vector:0.37.1-debian
    volumes:
      - ./vector.yaml:/vector.yaml
    command: [ "--config", "/vector.yaml" ]
    ports:
      - "4327:4317/tcp"
    networks:
      - log_network
  grafana:
    image: grafana/otel-lgtm:latest
    ports:
      - "4337:4317/tcp"
      - "3000:3000/tcp"
    networks:
      - log_network

networks:
  log_network: { }