receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: vector:4317
    tls:
      insecure: true
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlp ]