receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp/vector:
    endpoint: vector:4317
    tls:
      insecure: true
  otlp/grafana:
    endpoint: grafana:4317
    tls:
      insecure: true
  file:
    path: /tmp/logs.json
#    encoding: otlp_json
#  logging:
#    verbosity: detailed
#processors:
#  transform:
#    log_statements:
#      - context: log
#        statements:
#          - set(body, Concat([time, body], " "))
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      #      processors: [ transform ]
      exporters: [ otlp/grafana ]

# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/README.md#concat
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottllog
# https://opentelemetry.io/docs/collector/configuration/#pipelines
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/textencodingextension
#   - encoding support not there yet